version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: keyvault-db
    environment:
      POSTGRES_USER: keyvault
      POSTGRES_PASSWORD: keyvault
      POSTGRES_DB: keyvault
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keyvault"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./Backend
    container_name: keyvault-backend
    env_file:
      - ./Backend/.env
    environment:
      DATABASE_URL: postgresql://keyvault:keyvault@db:5432/keyvault
      PORT: 4000
      NODE_ENV: development
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Backend:/usr/src/app
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"

volumes:
  db_data:
